// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/git_manager.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(String)
  dco_decode_DartFn_Inputs_String_Output_unit_AnyhowException(dynamic raw);

  @protected
  FutureOr<String?> Function()
  dco_decode_DartFn_Inputs__Output_opt_String_AnyhowException(dynamic raw);

  @protected
  FutureOr<bool?> Function()
  dco_decode_DartFn_Inputs__Output_opt_box_autoadd_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<int?> Function()
  dco_decode_DartFn_Inputs__Output_opt_box_autoadd_i_32_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<(String, String)?> Function()
  dco_decode_DartFn_Inputs__Output_opt_box_autoadd_record_string_string_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<List<String>?> Function()
  dco_decode_DartFn_Inputs__Output_opt_list_String_AnyhowException(dynamic raw);

  @protected
  FutureOr<List<Commit>?> Function()
  dco_decode_DartFn_Inputs__Output_opt_list_commit_AnyhowException(dynamic raw);

  @protected
  FutureOr<List<(String, ConflictType)>?> Function()
  dco_decode_DartFn_Inputs__Output_opt_list_record_string_conflict_type_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<List<(String, int)>?> Function()
  dco_decode_DartFn_Inputs__Output_opt_list_record_string_i_32_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function()
  dco_decode_DartFn_Inputs__Output_unit_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(int)
  dco_decode_DartFn_Inputs_i_32_Output_unit_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(LogType, String)
  dco_decode_DartFn_Inputs_log_type_String_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, Map<String, String>>
  dco_decode_Map_String_Map_String_String_None_None(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, (int, int)> dco_decode_Map_String_record_i_32_i_32_None(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  WithLine dco_decode_TraitDef_WithLine(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  (String, String) dco_decode_box_autoadd_record_string_string(dynamic raw);

  @protected
  Commit dco_decode_commit(dynamic raw);

  @protected
  ConflictType dco_decode_conflict_type(dynamic raw);

  @protected
  Diff dco_decode_diff(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Commit> dco_decode_list_commit(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, ConflictType)> dco_decode_list_record_string_conflict_type(
    dynamic raw,
  );

  @protected
  List<(String, int)> dco_decode_list_record_string_i_32(dynamic raw);

  @protected
  List<(String, Map<String, String>)>
  dco_decode_list_record_string_map_string_string_none(dynamic raw);

  @protected
  List<(String, (int, int))> dco_decode_list_record_string_record_i_32_i_32(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<WorkdirDiffLine> dco_decode_list_workdir_diff_line(dynamic raw);

  @protected
  LogType dco_decode_log_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  (String, String)? dco_decode_opt_box_autoadd_record_string_string(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<Commit>? dco_decode_opt_list_commit(dynamic raw);

  @protected
  List<(String, ConflictType)>? dco_decode_opt_list_record_string_conflict_type(
    dynamic raw,
  );

  @protected
  List<(String, int)>? dco_decode_opt_list_record_string_i_32(dynamic raw);

  @protected
  (int, int) dco_decode_record_i_32_i_32(dynamic raw);

  @protected
  (String, ConflictType) dco_decode_record_string_conflict_type(dynamic raw);

  @protected
  (String, int) dco_decode_record_string_i_32(dynamic raw);

  @protected
  (String, Map<String, String>) dco_decode_record_string_map_string_string_none(
    dynamic raw,
  );

  @protected
  (String, (int, int)) dco_decode_record_string_record_i_32_i_32(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WorkdirDiffLine dco_decode_workdir_diff_line(dynamic raw);

  @protected
  WorkdirFileDiff dco_decode_workdir_file_diff(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, Map<String, String>>
  sse_decode_Map_String_Map_String_String_None_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, (int, int)> sse_decode_Map_String_record_i_32_i_32_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_box_autoadd_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  Commit sse_decode_commit(SseDeserializer deserializer);

  @protected
  ConflictType sse_decode_conflict_type(SseDeserializer deserializer);

  @protected
  Diff sse_decode_diff(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Commit> sse_decode_list_commit(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, ConflictType)> sse_decode_list_record_string_conflict_type(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, int)> sse_decode_list_record_string_i_32(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Map<String, String>)>
  sse_decode_list_record_string_map_string_string_none(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, (int, int))> sse_decode_list_record_string_record_i_32_i_32(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkdirDiffLine> sse_decode_list_workdir_diff_line(
    SseDeserializer deserializer,
  );

  @protected
  LogType sse_decode_log_type(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  (String, String)? sse_decode_opt_box_autoadd_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<Commit>? sse_decode_opt_list_commit(SseDeserializer deserializer);

  @protected
  List<(String, ConflictType)>? sse_decode_opt_list_record_string_conflict_type(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, int)>? sse_decode_opt_list_record_string_i_32(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_i_32_i_32(SseDeserializer deserializer);

  @protected
  (String, ConflictType) sse_decode_record_string_conflict_type(
    SseDeserializer deserializer,
  );

  @protected
  (String, int) sse_decode_record_string_i_32(SseDeserializer deserializer);

  @protected
  (String, Map<String, String>) sse_decode_record_string_map_string_string_none(
    SseDeserializer deserializer,
  );

  @protected
  (String, (int, int)) sse_decode_record_string_record_i_32_i_32(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WorkdirDiffLine sse_decode_workdir_diff_line(SseDeserializer deserializer);

  @protected
  WorkdirFileDiff sse_decode_workdir_file_diff(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs__Output_opt_String_AnyhowException(
    FutureOr<String?> Function() self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs__Output_opt_box_autoadd_bool_AnyhowException(
    FutureOr<bool?> Function() self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs__Output_opt_box_autoadd_i_32_AnyhowException(
    FutureOr<int?> Function() self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs__Output_opt_box_autoadd_record_string_string_AnyhowException(
    FutureOr<(String, String)?> Function() self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs__Output_opt_list_String_AnyhowException(
    FutureOr<List<String>?> Function() self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs__Output_opt_list_commit_AnyhowException(
    FutureOr<List<Commit>?> Function() self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs__Output_opt_list_record_string_conflict_type_AnyhowException(
    FutureOr<List<(String, ConflictType)>?> Function() self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs__Output_opt_list_record_string_i_32_AnyhowException(
    FutureOr<List<(String, int)>?> Function() self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs__Output_unit_AnyhowException(
    FutureOr<void> Function() self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_i_32_Output_unit_AnyhowException(
    FutureOr<void> Function(int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_log_type_String_Output_unit_AnyhowException(
    FutureOr<void> Function(LogType, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_Map_String_String_None_None(
    Map<String, Map<String, String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_record_i_32_i_32_None(
    Map<String, (int, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_commit(Commit self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_type(ConflictType self, SseSerializer serializer);

  @protected
  void sse_encode_diff(Diff self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_commit(List<Commit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_conflict_type(
    List<(String, ConflictType)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_i_32(
    List<(String, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_map_string_string_none(
    List<(String, Map<String, String>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_record_i_32_i_32(
    List<(String, (int, int))> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workdir_diff_line(
    List<WorkdirDiffLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_type(LogType self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_record_string_string(
    (String, String)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_commit(List<Commit>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_record_string_conflict_type(
    List<(String, ConflictType)>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_record_string_i_32(
    List<(String, int)>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_i_32_i_32((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_conflict_type(
    (String, ConflictType) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_i_32(
    (String, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_map_string_string_none(
    (String, Map<String, String>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_record_i_32_i_32(
    (String, (int, int)) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_workdir_diff_line(
    WorkdirDiffLine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workdir_file_diff(
    WorkdirFileDiff self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
